import type { UseChatAgentProjectionArgs } from "@/state/chat/agent/projection-types.ts";
import { useChatAgentMessageProjection } from "@/state/chat/agent/use-message-projection.ts";
import { useChatAgentOrderingMaintenance } from "@/state/chat/agent/use-ordering-maintenance.ts";
import { useChatAgentStreamFinalization } from "@/state/chat/agent/use-stream-finalization.ts";

export function useChatAgentProjection({
  activeBackgroundAgentCountRef,
  activeStreamRunIdRef,
  agentMessageBindings,
  agentLifecycleLedgerRef,
  agentMessageIdByIdRef,
  agentOrderingStateRef,
  agentType,
  awaitedStreamRunIdsRef,
  backgroundAgentMessageIdRef,
  completionOrderingEventByAgentRef,
  continueQueuedConversation,
  deferredCompleteTimeoutRef,
  deferredPostCompleteDeltasByAgentRef,
  deleteAgentMessageBinding,
  doneRenderedSequenceByAgentRef,
  finalizeThinkingSourceTracking,
  getActiveStreamRunId,
  hasRunningToolRef,
  isAgentOnlyStreamRef,
  isStreamingRef,
  lastStreamedMessageIdRef,
  lastStreamingContentRef,
  messages,
  parallelAgents,
  parallelAgentsRef,
  pendingCompleteRef,
  resolveTrackedRun,
  setActiveBackgroundAgentCount,
  setBackgroundAgentMessageId,
  setMessagesWindowed,
  setParallelAgents,
  stopSharedStreamState,
  streamingMessageIdRef,
  streamingStartRef,
  todoItemsRef,
  hasRunningTool,
  streamingMessageId,
  lastStreamedMessageId,
  backgroundAgentMessageId,
  workflowActiveRef,
}: UseChatAgentProjectionArgs) {
  const { handleAgentDoneRendered } = useChatAgentMessageProjection({
    activeStreamRunIdRef,
    agentMessageBindings,
    agentLifecycleLedgerRef,
    agentMessageIdByIdRef,
    agentOrderingStateRef,
    agentType,
    backgroundAgentMessageIdRef,
    completionOrderingEventByAgentRef,
    doneRenderedSequenceByAgentRef,
    lastStreamedMessageIdRef,
    parallelAgents,
    setBackgroundAgentMessageId,
    setMessagesWindowed,
    streamingMessageId,
    lastStreamedMessageId,
    backgroundAgentMessageId,
    streamingMessageIdRef,
    streamingStartRef,
    workflowActiveRef,
  });

  useChatAgentOrderingMaintenance({
    agentMessageIdByIdRef,
    agentOrderingStateRef,
    completionOrderingEventByAgentRef,
    deferredPostCompleteDeltasByAgentRef,
    deleteAgentMessageBinding,
    doneRenderedSequenceByAgentRef,
    parallelAgents,
  });

  useChatAgentStreamFinalization({
    activeBackgroundAgentCountRef,
    awaitedStreamRunIdsRef,
    continueQueuedConversation,
    deferredCompleteTimeoutRef,
    finalizeThinkingSourceTracking,
    getActiveStreamRunId,
    hasRunningToolRef,
    isAgentOnlyStreamRef,
    isStreamingRef,
    lastStreamingContentRef,
    messages,
    parallelAgents,
    parallelAgentsRef,
    pendingCompleteRef,
    resolveTrackedRun,
    setActiveBackgroundAgentCount,
    setBackgroundAgentMessageId,
    setMessagesWindowed,
    setParallelAgents,
    stopSharedStreamState,
    streamingMessageIdRef,
    streamingStartRef,
    todoItemsRef,
    hasRunningTool,
  });

  return { handleAgentDoneRendered };
}
