/**
 * Export engine — handoff bundle packaging.
 *
 * Writes the deterministic parts of the handoff bundle (no LLM call):
 *   - handoff-prompt.md  — ready-to-use prompt for Claude Code
 *   - README.md          — how to use the bundle
 *
 * The exporter stage (LLM) handles copying design files, writing
 * design-intent.md and component-specs.md since those require
 * understanding the generated design content.
 */

import { writeFile, mkdir, copyFile } from "node:fs/promises";
import path from "node:path";
import type { DesignSystemData } from "./design-system.ts";

export interface HandoffBundleOptions {
  designSystem: DesignSystemData;
  prompt: string;
  outputType: string;
}

/**
 * Write the deterministic handoff bundle files.
 *
 * The exporter stage is responsible for:
 *   - Copying design files (index.html, styles.css, script.js) to design/
 *   - Writing design-intent.md from transcript analysis
 *   - Writing component-specs.md from design analysis
 *
 * This function writes the remaining deterministic files:
 *   - Design.md (copy of the design system)
 *   - handoff-prompt.md (ready-to-use implementation prompt)
 *   - README.md (bundle documentation)
 */
export async function writeHandoffBundle(
  finalDesignDir: string,
  opts: HandoffBundleOptions,
): Promise<void> {
  await mkdir(finalDesignDir, { recursive: true });
  await mkdir(path.join(finalDesignDir, "design"), { recursive: true });

  // Copy Design.md
  await copyFile(
    opts.designSystem.path,
    path.join(finalDesignDir, "Design.md"),
  );

  // Write handoff-prompt.md
  const handoffPrompt = buildHandoffPrompt(opts);
  await writeFile(
    path.join(finalDesignDir, "handoff-prompt.md"),
    handoffPrompt,
    "utf-8",
  );

  // Write README.md
  const readme = buildReadme(opts);
  await writeFile(
    path.join(finalDesignDir, "README.md"),
    readme,
    "utf-8",
  );
}

function buildHandoffPrompt(opts: HandoffBundleOptions): string {
  return `# Design Handoff — Implementation Prompt

Use this prompt with Claude Code to implement the design in this bundle.

## Original Design Request

${opts.prompt}

## Output Type

${opts.outputType}

## Instructions

1. Read \`Design.md\` for the complete design system (colors, typography, spacing, components).
2. Open \`design/index.html\` in a browser to see the reference design.
3. Read \`design-intent.md\` for the design rationale and key decisions.
4. Read \`component-specs.md\` for individual component specifications.
5. Implement the design using the design system tokens from Design.md.
6. Match the reference design in \`design/\` as closely as possible.
7. Use semantic HTML, CSS custom properties for tokens, and progressive enhancement.

## Design System Tokens

The design tokens are defined in \`Design.md\`. Use CSS custom properties:

\`\`\`css
:root {
  /* Import all tokens from Design.md as custom properties */
}
\`\`\`

## Quality Checklist

- [ ] All colors match Design.md tokens
- [ ] Typography follows the defined scale
- [ ] Spacing uses the defined base unit
- [ ] Components match the identified patterns
- [ ] No AI slop anti-patterns (gradient text, side-stripe borders, reflex fonts)
- [ ] Responsive at common breakpoints
- [ ] Accessible (WCAG 2.1 AA)
`;
}

function buildReadme(opts: HandoffBundleOptions): string {
  return `# Design Handoff Bundle

Generated by the \`open-claude-design\` workflow.

## Contents

| File | Description |
|------|-------------|
| \`design/index.html\` | Generated HTML prototype |
| \`design/styles.css\` | Generated CSS styles |
| \`design/script.js\` | Generated JavaScript |
| \`Design.md\` | Design system tokens (colors, typography, spacing) |
| \`design-intent.md\` | Design rationale and key decisions |
| \`component-specs.md\` | Component specifications |
| \`handoff-prompt.md\` | Ready-to-use prompt for Claude Code |

## Usage

### Preview the Design

Open \`design/index.html\` in a browser to view the generated design.

### Implement with Claude Code

\`\`\`bash
# From the project root, run:
claude "$(cat ${opts.outputType === "component" ? "component-specs.md" : "handoff-prompt.md"})"
\`\`\`

### Design System Reference

All design tokens are in \`Design.md\`. Use these tokens when implementing
to ensure visual consistency with the generated design.

## Original Request

${opts.prompt}
`;
}
