import type {
  UseChatStreamLifecycleArgs,
  UseChatStreamLifecycleResult,
} from "@/state/chat/stream/lifecycle-types.ts";
import { useChatStreamCompletion } from "@/state/chat/stream/use-completion.ts";
import { useChatStreamErrors } from "@/state/chat/stream/use-errors.ts";
import { useChatStreamStartup } from "@/state/chat/stream/use-startup.ts";

export function useChatStreamLifecycle({
  activeBackgroundAgentCountRef,
  activeStreamRunIdRef,
  agentType,
  awaitedStreamRunIdsRef,
  bindTrackedRunToMessage,
  clearDeferredCompletion,
  continueAssistantStreamInPlaceRef,
  continueQueuedConversationRef,
  currentModelRef,
  deferredCompleteTimeoutRef,
  finalizeThinkingSourceTracking,
  getActiveStreamRunId,
  hasRunningToolRef,
  isAgentOnlyStreamRef,
  isStreamingRef,
  lastStreamingContentRef,
  lastTurnFinishReasonRef,
  nextRunIdFloorRef,
  onStreamMessage,
  parallelAgentsRef,
  pendingCompleteRef,
  resetConsumers,
  resetTodoItemsForNewStream,
  resetThinkingSourceTracking,
  resolveTrackedRun,
  runningAskQuestionToolIdsRef,
  runningBlockingToolIdsRef,
  sendBackgroundMessageToAgent,
  setActiveBackgroundAgentCount,
  setBackgroundAgentMessageId,
  setIsStreaming,
  setLastStreamedMessageId,
  setMessagesWindowed,
  setParallelAgents,
  setStreamingMessageId,
  setToolCompletionVersion,
  shouldHideActiveStreamContent,
  startAssistantStreamRef,
  startTrackedAssistantRun,
  stopSharedStreamState,
  streamingMessageIdRef,
  streamingMetaRef,
  streamingStartRef,
  todoItemsRef,
  toolMessageIdByIdRef,
  toolNameByIdRef,
  wasInterruptedRef,
}: UseChatStreamLifecycleArgs): UseChatStreamLifecycleResult {
  const { handleStreamStartupError, terminateAgentLifecycleContractViolation } = useChatStreamErrors({
    continueQueuedConversationRef,
    currentModelRef,
    finalizeThinkingSourceTracking,
    lastStreamingContentRef,
    resolveTrackedRun,
    setMessagesWindowed,
    stopSharedStreamState,
    streamingMessageIdRef,
  });

  const { handleStreamComplete } = useChatStreamCompletion({
    activeBackgroundAgentCountRef,
    activeStreamRunIdRef,
    agentType,
    awaitedStreamRunIdsRef,
    continueAssistantStreamInPlaceRef,
    continueQueuedConversationRef,
    currentModelRef,
    deferredCompleteTimeoutRef,
    finalizeThinkingSourceTracking,
    getActiveStreamRunId,
    hasRunningToolRef,
    isAgentOnlyStreamRef,
    lastStreamingContentRef,
    parallelAgentsRef,
    pendingCompleteRef,
    resolveTrackedRun,
    runningAskQuestionToolIdsRef,
    runningBlockingToolIdsRef,
    sendBackgroundMessageToAgent,
    setActiveBackgroundAgentCount,
    setBackgroundAgentMessageId,
    setLastStreamedMessageId,
    setMessagesWindowed,
    setParallelAgents,
    setToolCompletionVersion,
    shouldHideActiveStreamContent,
    startAssistantStreamRef,
    stopSharedStreamState,
    streamingMessageIdRef,
    streamingMetaRef,
    streamingStartRef,
    todoItemsRef,
    toolMessageIdByIdRef,
    toolNameByIdRef,
    wasInterruptedRef,
  });

  const {
    continueAssistantStreamInPlace,
    startAssistantStream,
  } = useChatStreamStartup({
    activeStreamRunIdRef,
    bindTrackedRunToMessage,
    clearDeferredCompletion,
    handleStreamStartupError,
    hasRunningToolRef,
    isAgentOnlyStreamRef,
    isStreamingRef,
    lastStreamingContentRef,
    nextRunIdFloorRef,
    lastTurnFinishReasonRef,
    onStreamMessage,
    resetConsumers,
    resetThinkingSourceTracking,
    resetTodoItemsForNewStream,
    runningAskQuestionToolIdsRef,
    runningBlockingToolIdsRef,
    setIsStreaming,
    setLastStreamedMessageId,
    setMessagesWindowed,
    setStreamingMessageId,
    startTrackedAssistantRun,
    streamingStartRef,
    toolMessageIdByIdRef,
    toolNameByIdRef,
  });

  return {
    continueAssistantStreamInPlace,
    handleStreamComplete,
    handleStreamStartupError,
    startAssistantStream,
    terminateAgentLifecycleContractViolation,
  };
}
