import { useCallback } from "react";
import { useChatDispatchController } from "@/state/chat/controller/use-dispatch-controller.ts";
import { useChatKeyboard } from "@/state/chat/keyboard/index.ts";
import { useChatRenderModel } from "@/state/chat/shell/index.ts";
import { useComposerController } from "@/state/chat/composer/index.ts";
import { buildUiControllerChatShellProps } from "@/state/chat/controller/use-ui-controller-stack/chat-shell-props.ts";
import type { UseChatUiControllerStackArgs } from "@/state/chat/controller/use-ui-controller-stack/types.ts";

export function useChatUiControllerStack({
  agentType,
  app,
  hitl,
  isStreaming,
  messageQueue,
  messages,
  orchestration,
  runtime,
  deferredCommandQueueRef,
  eventBus,
  setIsStreaming,
  setMessagesWindowed,
  setStreamingMeta,
  shellState,
  streamingMeta,
  workflowState,
}: UseChatUiControllerStackArgs) {
  const {
    createSubagentSession,
    ensureSession,
    getModelDisplayInfo,
    getSession,
    initialModelId,
    initialPrompt,
    model,
    modelOps,
    onCommandExecutionTelemetry,
    onExit,
    onInterrupt,
    onModelChange,
    onResetSession,
    onSendMessage,
    onSessionMcpServersChange,
    onTerminateBackgroundAgents,
    setStreamingState,
    tier,
    version,
    workingDir,
  } = app;

  const {
    activeHitlToolCallIdRef,
    activeQuestion,
    handleAgentDoneRendered,
    handleQuestionAnswer,
    resetHitlState,
  } = hitl;

  const {
    availableModels,
    clipboard,
    commandStyleIdRef,
    copyRendererSelection,
    currentModelId,
    currentReasoningEffort,
    currentModelRef,
    dispatchDeferredCommandMessageRef,
    dispatchQueuedMessageRef,
    displayModel,
    handleMouseUp,
    hasRendererSelection,
    historyBufferMessages,
    inputFocused,
    inputSyntaxStyle,
    markdownSyntaxStyle,
    mcpServerToggles,
    scrollAcceleration,
    scrollboxRef,
    setAvailableModels,
    setCurrentModelDisplayName,
    setCurrentModelId,
    setCurrentReasoningEffort,
    setMcpServerToggles,
    setShowModelSelector,
    setShowTodoPanel,
    setTranscriptMode,
    setTheme,
    showModelSelector,
    showTodoPanel,
    tasksExpanded,
    themeColors,
    isVerbose,
    toggleVerbose,
    toggleTheme,
    transcriptMode,
    waitForUserInputResolverRef,
    workflowActiveRef,
    actions: {
      appendCompactionSummaryAndSync,
      appendHistoryBufferAndSync,
      clearHistoryBufferAndSync,
    },
  } = shellState;

  const {
    continueQueuedConversation,
    dynamicPlaceholder,
    emitMessageSubmitTelemetry,
    finalizeTaskItemsOnInterrupt,
    updateWorkflowState,
  } = orchestration;

  const {
    state: {
      activeBackgroundAgentCount,
      compactionSummary,
      parallelAgents,
      showCompactionHistory,
      streamingElapsedMs,
      todoItems,
      workflowSessionDir,
    },
    setters: {
      setActiveBackgroundAgentCount,
      setCompactionSummary,
      setIsAutoCompacting,
      setParallelAgents,
      setShowCompactionHistory,
      setTodoItems,
      setWorkflowSessionDir,
      setWorkflowSessionId,
    },
    refs: {
      activeBackgroundAgentCountRef,
      activeStreamRunIdRef,
      autoCompactionIndicatorRef,
      awaitedStreamRunIdsRef,
      backgroundAgentMessageIdRef,
      backgroundProgressSnapshotRef,
      hasRunningToolRef,
      isAgentOnlyStreamRef,
      isStreamingRef,
      lastStreamedMessageIdRef,
      lastStreamingContentRef,
      loadedSkillsRef,
      parallelAgentsRef,
      parallelInterruptHandlerRef,
      pendingCompleteRef,
      runningAskQuestionToolIdsRef,
      streamingMessageIdRef,
      streamingMetaRef,
      streamingStartRef,
      todoItemsRef,
      wasInterruptedRef,
      workflowSessionDirRef,
      workflowSessionIdRef,
      workflowTaskIdsRef,
    },
    actions: {
      appendSkillLoadIndicator,
      clearDeferredCompletion,
      finalizeThinkingSourceTracking,
      getActiveStreamRunId,
      getOwnershipTracker,
      resetLoadedSkillTracking,
      resolveTrackedRun,
      separateAndInterruptAgents,
      setBackgroundAgentMessageId,
      setLastStreamedMessageId,
      setStreamingMessageId,
      shouldHideActiveStreamContent,
      startAssistantStream,
      stopSharedStreamState,
      trackAwaitedRun,
    },
  } = runtime;

  const {
    addMessage,
    executeCommand,
    handleModelSelect,
    handleModelSelectorCancel,
    sendMessage,
  } = useChatDispatchController({
    activeStreamRunIdRef,
    agentType,
    appendCompactionSummaryAndSync,
    appendHistoryBufferAndSync,
    appendSkillLoadIndicator,
    autoCompactionIndicatorRef,
    backgroundProgressSnapshotRef,
    clearHistoryBufferAndSync,
    continueQueuedConversation,
    createSubagentSession,
    currentModelRef,
    deferredCommandQueueRef,
    dispatchDeferredCommandMessageRef,
    dispatchQueuedMessageRef,
    emitMessageSubmitTelemetry,
    ensureSession,
    eventBus,
    getOwnershipTracker,
    getModelDisplayInfo,
    getSession,
    hasRunningToolRef,
    initialPrompt,
    isAgentOnlyStreamRef,
    isStreaming,
    isStreamingRef,
    loadedSkillsRef,
    mcpServerToggles,
    messages,
    modelOps,
    onCommandExecutionTelemetry,
    onModelChange,
    onResetSession,
    onSendMessage,
    onSessionMcpServersChange,
    pendingCompleteRef,
    parallelInterruptHandlerRef,
    resetLoadedSkillTracking,
    runningAskQuestionToolIdsRef,
    setAvailableModels,
    setCompactionSummary,
    setCurrentModelDisplayName,
    setCurrentModelId,
    setCurrentReasoningEffort,
    setIsAutoCompacting,
    setIsStreaming,
    setLastStreamedMessageId,
    setMcpServerToggles,
    setMessagesWindowed,
    setParallelAgents,
    setShowCompactionHistory,
    setShowModelSelector,
    setStreamingMessageId,
    setStreamingMeta,
    setStreamingState,
    setTheme,
    setTodoItems,
    setTranscriptMode,
    setWorkflowSessionDir,
    setWorkflowSessionId,
    startAssistantStream,
    stopSharedStreamState,
    streamingMessageIdRef,
    streamingMetaRef,
    streamingStartRef,
    todoItemsRef,
    toggleTheme,
    trackAwaitedRun,
    updateWorkflowState,
    waitForUserInputResolverRef,
    workflowActiveRef,
    workflowSessionDirRef,
    workflowSessionIdRef,
    workflowState,
    workflowTaskIdsRef,
  });

  const {
    autocompleteSuggestions,
    handleAutocompleteIndexChange,
    handleAutocompleteSelect,
    handleBracketedPaste,
    handleInputChange,
    handleSubmit,
    handleTextareaContentChange,
    handleTextareaCursorChange,
    historyIndexRef,
    historyNavigatingRef,
    inputScrollbar,
    isEditingQueue,
    kittyKeyboardDetectedRef,
    normalizePastedText,
    promptHistoryRef,
    savedInputRef,
    setIsEditingQueue,
    syncInputScrollbar,
    textareaKeyBindings,
    textareaRef,
  } = useComposerController({
    activeQuestion,
    addMessage,
    agentType,
    clipboard,
    clearDeferredCompletion,
    commandStyleIdRef,
    currentModelRef,
    emitMessageSubmitTelemetry,
    executeCommand,
    finalizeTaskItemsOnInterrupt,
    finalizeThinkingSourceTracking,
    getActiveStreamRunId,
    isStreamingRef,
    lastStreamingContentRef,
    messageQueue,
    onInterrupt,
    parallelAgentsRef,
    parallelInterruptHandlerRef,
    resolveTrackedRun,
    runningAskQuestionToolIdsRef,
    sendMessage,
    separateAndInterruptAgents,
    setIsStreaming,
    setMessagesWindowed,
    setParallelAgents,
    setTodoItems,
    setWorkflowSessionDir,
    setWorkflowSessionId,
    shouldHideActiveStreamContent,
    showModelSelector,
    stopSharedStreamState,
    streamingMessageIdRef,
    streamingMetaRef,
    streamingStartRef,
    todoItemsRef,
    updateWorkflowState,
    waitForUserInputResolverRef,
    workflowSessionDirRef,
    workflowSessionIdRef,
    workflowState,
    workflowTaskIdsRef,
  });

  const handleCopy = useCallback(() => {
    const textarea = textareaRef.current;
    if (textarea?.hasSelection()) {
      const selectedText = textarea.getSelectedText();
      if (selectedText) {
        clipboard.copy(selectedText);
        return;
      }
    }
    copyRendererSelection();
  }, [clipboard, copyRendererSelection, textareaRef]);

  const {
    ctrlCPressed,
    ctrlFPressed,
  } = useChatKeyboard({
    activeBackgroundAgentCountRef,
    activeQuestion,
    activeHitlToolCallIdRef,
    addMessage,
    autocompleteSuggestions,
    awaitedStreamRunIdsRef,
    backgroundAgentMessageIdRef,
    clipboard,
    clearDeferredCompletion,
    continueQueuedConversation,
    emitMessageSubmitTelemetry,
    executeCommand,
    finalizeTaskItemsOnInterrupt,
    finalizeThinkingSourceTracking,
    getActiveStreamRunId,
    handleCopy,
    handleInputChange,
    handleTextareaContentChange,
    hasRendererSelection,
    historyIndexRef,
    historyNavigatingRef,
    isEditingQueue,
    isStreaming,
    isStreamingRef,
    kittyKeyboardDetectedRef,
    lastStreamedMessageIdRef,
    lastStreamingContentRef,
    messageQueue,
    normalizePastedText,
    onExit,
    onInterrupt,
    onTerminateBackgroundAgents,
    parallelAgents,
    parallelAgentsRef,
    parallelInterruptHandlerRef,
    promptHistoryRef,
    resetHitlState,
    resolveTrackedRun,
    savedInputRef,
    scrollboxRef,
    separateAndInterruptAgents,
    setActiveBackgroundAgentCount,
    setBackgroundAgentMessageId,
    setIsEditingQueue,
    setMessagesWindowed,
    setParallelAgents,
    setShowTodoPanel,
    setTranscriptMode,
    shouldHideActiveStreamContent,
    showModelSelector,
    stopSharedStreamState,
    streamingMessageIdRef,
    streamingMetaRef,
    streamingStartRef,
    syncInputScrollbar,
    textareaRef,
    toggleVerbose,
    updateWorkflowState,
    wasInterruptedRef,
    waitForUserInputResolverRef,
    workflowActiveRef,
    workflowState,
  });

  const { messageContent } = useChatRenderModel({
    activeBackgroundAgentCount,
    activeQuestion,
    backgroundAgentMessageId: backgroundAgentMessageIdRef.current,
    handleAgentDoneRendered,
    isVerbose,
    lastStreamedMessageId: lastStreamedMessageIdRef.current,
    markdownSyntaxStyle,
    messages,
    parallelAgents,
    showTodoPanel,
    streamingElapsedMs,
    streamingMessageId: streamingMessageIdRef.current,
    streamingMeta,
    tasksExpanded,
    todoItems,
    workflowSessionDir,
    workflowState,
  });

  const chatShellProps = buildUiControllerChatShellProps({
    activeQuestion,
    availableModels,
    autocompleteInput: workflowState.autocompleteInput,
    autocompleteMode: workflowState.autocompleteMode,
    autocompleteSelectedIndex: workflowState.selectedSuggestionIndex,
    autocompleteSuggestions,
    argumentHint: workflowState.argumentHint,
    compactionSummary,
    ctrlCPressed,
    ctrlFPressed,
    currentModelId,
    currentReasoningEffort,
    displayModel,
    dynamicPlaceholder,
    handleAutocompleteIndexChange,
    handleAutocompleteSelect,
    handleBracketedPaste,
    handleModelSelect,
    handleModelSelectorCancel,
    handleMouseUp,
    handleQuestionAnswer,
    handleSubmit,
    handleTextareaContentChange,
    handleTextareaCursorChange,
    historyBufferMessages,
    initialModelId,
    inputSyntaxStyle,
    inputFocused,
    inputScrollbar,
    isEditingQueue,
    isStreaming,
    messageContent,
    messageCount: messages.length,
    messageQueue,
    messages,
    model,
    parallelAgents,
    scrollAcceleration,
    scrollboxRef,
    setIsEditingQueue,
    showAutocomplete: workflowState.showAutocomplete,
    showCompactionHistory,
    showModelSelector,
    streamingMeta,
    textareaKeyBindings,
    textareaRef,
    themeColors,
    tier,
    transcriptMode,
    version,
    workingDir,
    workflowState,
  });

  return { chatShellProps };
}
