import type { UseChatUiControllerStackArgs } from "./types.ts";

/**
 * Flattens the deeply nested UseChatUiControllerStackArgs into a single
 * flat namespace so that downstream sub-hooks can be called with simple
 * spread syntax rather than 80+ explicit property assignments.
 */
export function useOrchestrationState(args: UseChatUiControllerStackArgs) {
  const { app, hitl, shellState, orchestration, runtime, ...topLevel } = args;

  // ── App ──────────────────────────────────────────────────────────────
  const {
    createSubagentSession,
    registerTool,
    streamWithSession,
    ensureSession,
    getModelDisplayInfo,
    getSession,
    initialModelId,
    initialPrompt,
    model,
    modelOps,
    onCommandExecutionTelemetry,
    onExit,
    onInterrupt,
    onModelChange,
    onResetSession,
    onSendMessage,
    onSessionMcpServersChange,
    onTerminateBackgroundAgents,
    setStreamingState,
    tier,
    version,
    workingDir,
  } = app;

  // ── HITL ─────────────────────────────────────────────────────────────
  const {
    activeHitlToolCallIdRef,
    activeQuestion,
    handleAgentDoneRendered,
    handleQuestionAnswer,
    resetHitlState,
  } = hitl;

  // ── Shell State ──────────────────────────────────────────────────────
  const {
    availableModels,
    clipboard,
    commandStyleIdRef,
    copyRendererSelection,
    currentModelId,
    currentReasoningEffort,
    currentModelRef,
    dispatchDeferredCommandMessageRef,
    dispatchQueuedMessageRef,
    displayModel,
    handleMouseUp,
    hasRendererSelection,
    historyBufferMessages,
    inputFocused,
    inputSyntaxStyle,
    markdownSyntaxStyle,
    mcpServerToggles,
    scrollAcceleration,
    scrollboxRef,
    setAvailableModels,
    setCurrentModelDisplayName,
    setCurrentModelId,
    setCurrentReasoningEffort,
    setMcpServerToggles,
    setShowModelSelector,
    setShowTodoPanel,
    setTranscriptMode,
    setTheme,
    showModelSelector,
    showTodoPanel,
    tasksExpanded,
    themeColors,
    toggleVerbose,
    toggleTheme,
    transcriptMode,
    conductorInterruptRef,
    conductorResumeRef,
    waitForUserInputResolverRef,
    workflowActiveRef,
    actions: {
      appendCompactionSummaryAndSync,
      appendHistoryBufferAndSync,
      clearHistoryBufferAndSync,
    },
  } = shellState;

  // ── Orchestration ────────────────────────────────────────────────────
  const {
    continueQueuedConversation,
    dynamicPlaceholder,
    emitMessageSubmitTelemetry,
    finalizeTaskItemsOnInterrupt,
    updateWorkflowState,
  } = orchestration;

  // ── Runtime ──────────────────────────────────────────────────────────
  const {
    state: {
      activeBackgroundAgentCount,
      compactionSummary,
      parallelAgents,
      showCompactionHistory,
      streamingElapsedMs,
      todoItems,
      workflowSessionDir,
      workflowSessionId,
    },
    setters: {
      setActiveBackgroundAgentCount,
      setCompactionSummary,
      setIsAutoCompacting,
      setParallelAgents,
      setShowCompactionHistory,
      setTodoItems,
      setWorkflowSessionDir,
      setWorkflowSessionId,
    },
    refs: {
      activeBackgroundAgentCountRef,
      activeStreamRunIdRef,
      autoCompactionIndicatorRef,
      awaitedStreamRunIdsRef,
      backgroundAgentMessageIdRef,
      backgroundProgressSnapshotRef,
      hasRunningToolRef,
      isAgentOnlyStreamRef,
      isStreamingRef,
      lastStreamedMessageIdRef,
      lastStreamingContentRef,
      loadedSkillsRef,
      parallelAgentsRef,
      parallelInterruptHandlerRef,
      pendingCompleteRef,
      runningAskQuestionToolIdsRef,
      streamingMessageIdRef,
      streamingMetaRef,
      streamingStartRef,
      todoItemsRef,
      wasInterruptedRef,
      workflowSessionDirRef,
      workflowSessionIdRef,
      workflowTaskIdsRef,
    },
    actions: {
      appendSkillLoadIndicator,
      clearDeferredCompletion,
      finalizeThinkingSourceTracking,
      getActiveStreamRunId,
      getOwnershipTracker,
      resetLoadedSkillTracking,
      resolveTrackedRun,
      separateAndInterruptAgents,
      setLastStreamedMessageId,
      setStreamingMessageId,
      shouldHideActiveStreamContent,
      startAssistantStream,
      stopSharedStreamState,
      trackAwaitedRun,
    },
  } = runtime;

  // ── Derived ──────────────────────────────────────────────────────────
  const dequeueMessage = () => {
    const queued = topLevel.messageQueue.dequeue();
    return queued?.content ?? null;
  };

  return {
    // Top-level pass-through (agentType, isStreaming, messages, etc.)
    ...topLevel,
    // App
    createSubagentSession,
    registerTool,
    streamWithSession,
    ensureSession,
    getModelDisplayInfo,
    getSession,
    initialModelId,
    initialPrompt,
    model,
    modelOps,
    onCommandExecutionTelemetry,
    onExit,
    onInterrupt,
    onModelChange,
    onResetSession,
    onSendMessage,
    onSessionMcpServersChange,
    onTerminateBackgroundAgents,
    setStreamingState,
    tier,
    version,
    workingDir,
    // HITL
    activeHitlToolCallIdRef,
    activeQuestion,
    handleAgentDoneRendered,
    handleQuestionAnswer,
    resetHitlState,
    // Shell state
    availableModels,
    clipboard,
    commandStyleIdRef,
    copyRendererSelection,
    currentModelId,
    currentReasoningEffort,
    currentModelRef,
    dispatchDeferredCommandMessageRef,
    dispatchQueuedMessageRef,
    displayModel,
    handleMouseUp,
    hasRendererSelection,
    historyBufferMessages,
    inputFocused,
    inputSyntaxStyle,
    markdownSyntaxStyle,
    mcpServerToggles,
    scrollAcceleration,
    scrollboxRef,
    setAvailableModels,
    setCurrentModelDisplayName,
    setCurrentModelId,
    setCurrentReasoningEffort,
    setMcpServerToggles,
    setShowModelSelector,
    setShowTodoPanel,
    setTranscriptMode,
    setTheme,
    showModelSelector,
    showTodoPanel,
    tasksExpanded,
    themeColors,
    toggleVerbose,
    toggleTheme,
    transcriptMode,
    conductorInterruptRef,
    conductorResumeRef,
    waitForUserInputResolverRef,
    workflowActiveRef,
    appendCompactionSummaryAndSync,
    appendHistoryBufferAndSync,
    clearHistoryBufferAndSync,
    // Orchestration
    continueQueuedConversation,
    dynamicPlaceholder,
    emitMessageSubmitTelemetry,
    finalizeTaskItemsOnInterrupt,
    updateWorkflowState,
    // Runtime state
    activeBackgroundAgentCount,
    compactionSummary,
    parallelAgents,
    showCompactionHistory,
    streamingElapsedMs,
    todoItems,
    workflowSessionDir,
    workflowSessionId,
    // Runtime setters
    setActiveBackgroundAgentCount,
    setCompactionSummary,
    setIsAutoCompacting,
    setParallelAgents,
    setShowCompactionHistory,
    setTodoItems,
    setWorkflowSessionDir,
    setWorkflowSessionId,
    // Runtime refs
    activeBackgroundAgentCountRef,
    activeStreamRunIdRef,
    autoCompactionIndicatorRef,
    awaitedStreamRunIdsRef,
    backgroundAgentMessageIdRef,
    backgroundProgressSnapshotRef,
    hasRunningToolRef,
    isAgentOnlyStreamRef,
    isStreamingRef,
    lastStreamedMessageIdRef,
    lastStreamingContentRef,
    loadedSkillsRef,
    parallelAgentsRef,
    parallelInterruptHandlerRef,
    pendingCompleteRef,
    runningAskQuestionToolIdsRef,
    streamingMessageIdRef,
    streamingMetaRef,
    streamingStartRef,
    todoItemsRef,
    wasInterruptedRef,
    workflowSessionDirRef,
    workflowSessionIdRef,
    workflowTaskIdsRef,
    // Runtime actions
    appendSkillLoadIndicator,
    clearDeferredCompletion,
    finalizeThinkingSourceTracking,
    getActiveStreamRunId,
    getOwnershipTracker,
    resetLoadedSkillTracking,
    resolveTrackedRun,
    separateAndInterruptAgents,
    setLastStreamedMessageId,
    setStreamingMessageId,
    shouldHideActiveStreamContent,
    startAssistantStream,
    stopSharedStreamState,
    trackAwaitedRun,
    // Derived
    dequeueMessage,
  };
}

/** Inferred return type of useOrchestrationState for downstream consumers. */
export type OrchestrationState = ReturnType<typeof useOrchestrationState>;
