/**
 * Workflow discovery — finds workflow definitions from disk.
 *
 * Workflows are discovered from:
 *   1. .atomic/workflows/<name>/<agent>/index.ts (project-local)
 *   2. ~/.atomic/workflows/<name>/<agent>/index.ts (global)
 *
 * Project-local workflows take precedence over global ones with the same name.
 */

import { join } from "node:path";
import { readdir } from "node:fs/promises";
import { homedir } from "node:os";
import ignore from "ignore";
import type { AgentType, WorkflowInput } from "../types.ts";
import { WorkflowLoader } from "./loader.ts";

export interface DiscoveredWorkflow {
  name: string;
  agent: AgentType;
  path: string;
  source: "local" | "global" | "builtin";
}

function getLocalWorkflowsDir(projectRoot: string): string {
  return join(projectRoot, ".atomic", "workflows");
}

function getGlobalWorkflowsDir(): string {
  return join(homedir(), ".atomic", "workflows");
}

export const AGENTS: AgentType[] = ["copilot", "opencode", "claude"];
const AGENT_SET = new Set<string>(AGENTS);

/**
 * Default `.gitignore` content for a workflows directory.
 * Auto-generated during install; regenerated by discovery if missing.
 */
export const WORKFLOWS_GITIGNORE = [
  "node_modules/",
  "dist/",
  "build/",
  "coverage/",
  ".cache/",
  "*.log",
  "*.tsbuildinfo",
  "",
].join("\n");

/**
 * Load the `.gitignore` from a workflows directory, regenerating it if absent.
 * The workflows `.gitignore` is always auto-generated so a missing file
 * indicates an incomplete setup rather than an intentional absence.
 */
async function loadWorkflowsGitignore(workflowsDir: string): Promise<ignore.Ignore> {
  const gitignorePath = join(workflowsDir, ".gitignore");
  let content: string;
  try {
    content = await Bun.file(gitignorePath).text();
  } catch {
    // Missing — regenerate from the canonical template
    await Bun.write(gitignorePath, WORKFLOWS_GITIGNORE);
    content = WORKFLOWS_GITIGNORE;
  }
  return ignore().add(content);
}

/**
 * Discover workflows from a base directory by scanning workflow-name
 * directories first, then agent subdirectories within each.
 *
 * Layout: baseDir/<workflow_name>/<agent>/index.ts
 *
 * Entries are filtered against the `.gitignore` that lives inside the
 * workflows directory itself (auto-generated, regenerated if missing).
 */
async function discoverFromBaseDir(
  baseDir: string,
  source: "local" | "global",
  agentFilter?: AgentType,
): Promise<DiscoveredWorkflow[]> {
  const workflows: DiscoveredWorkflow[] = [];
  const agents = agentFilter ? [agentFilter] : AGENTS;
  const agentNames = new Set<string>(agents);

  let workflowEntries;
  try {
    workflowEntries = await readdir(baseDir, { withFileTypes: true });
  } catch {
    return workflows;
  }

  const ig = await loadWorkflowsGitignore(baseDir);

  for (const wfEntry of workflowEntries) {
    if (!wfEntry.isDirectory()) continue;
    if (wfEntry.name.startsWith(".")) continue;
    // Skip agent-named directories at root (they are not workflow names)
    if (AGENT_SET.has(wfEntry.name)) continue;
    // Skip directories matched by the workflows .gitignore.
    // Append "/" so directory-only patterns (e.g. "build/") match correctly.
    if (ig.ignores(wfEntry.name + "/")) continue;

    const workflowDir = join(baseDir, wfEntry.name);

    let agentEntries;
    try {
      agentEntries = await readdir(workflowDir, { withFileTypes: true });
    } catch {
      continue;
    }

    for (const agentEntry of agentEntries) {
      if (!agentEntry.isDirectory()) continue;
      if (!agentNames.has(agentEntry.name)) continue;

      const indexPath = join(workflowDir, agentEntry.name, "index.ts");
      const file = Bun.file(indexPath);
      if (await file.exists()) {
        workflows.push({
          name: wfEntry.name,
          agent: agentEntry.name as AgentType,
          path: indexPath,
          source,
        });
      }
    }
  }

  return workflows;
}

/**
 * Absolute path to the `builtin/` directory inside the SDK source tree.
 * Computed from this file's URL so it always resolves correctly regardless
 * of how the package was installed (dev checkout, global, bunx, etc.).
 */
const BUILTIN_WORKFLOWS_DIR = join(
  Bun.fileURLToPath(new URL("../workflows/builtin", import.meta.url)),
);

/**
 * Discover built-in workflows shipped as SDK modules.
 *
 * Scans `src/sdk/workflows/builtin/<name>/<agent>/index.ts` for known
 * workflow directories. Returns entries with `source: "builtin"`.
 */
async function discoverBuiltinWorkflows(
  agentFilter?: AgentType,
): Promise<DiscoveredWorkflow[]> {
  const results: DiscoveredWorkflow[] = [];
  const agents = agentFilter ? [agentFilter] : AGENTS;

  let workflowEntries;
  try {
    workflowEntries = await readdir(BUILTIN_WORKFLOWS_DIR, { withFileTypes: true });
  } catch {
    return results;
  }

  const workflowNames = workflowEntries
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  for (const name of workflowNames) {
    for (const agent of agents) {
      const indexPath = join(BUILTIN_WORKFLOWS_DIR, name, agent, "index.ts");
      if (await Bun.file(indexPath).exists()) {
        results.push({ name, agent, path: indexPath, source: "builtin" });
      }
    }
  }

  return results;
}

/**
 * Discover all available workflows from built-in, global, and local sources.
 * Optionally filter by agent.
 *
 * **Merge precedence:** `builtin > local > global`.
 *
 * Builtin names are **strictly reserved** — a user-defined local or
 * global workflow whose name matches any built-in workflow is dropped
 * entirely from discovery. It will not be registered, returned from
 * `findWorkflow`, appear in the interactive picker, or show up in
 * `atomic workflow -l`. This protects SDK-shipped workflows (e.g.
 * `ralph`) from being silently overridden or even visibly "competing
 * with" a user's own definition, which would otherwise be confusing
 * when someone tries to run the canonical version.
 *
 * Reservation is by **name only**, across all agents: if a builtin
 * defines `ralph` for any agent, a local `ralph` for any other agent is
 * also dropped. Local still overrides global for every non-builtin
 * name, so project-scoped customisation of user-scoped workflows
 * continues to work.
 *
 * By default, the result is **merged by precedence** — if a workflow is
 * defined in both local and global sources, only the higher-precedence
 * entry is returned. This is the right shape for `findWorkflow`, which
 * needs the single resolved entry per (name, agent) pair.
 *
 * Pass `{ merge: false }` to get the **unmerged** result — local and
 * global contribute their entries independently, so `--list` can show
 * both a local and a global copy of the same workflow when they coexist
 * on disk. (Builtin reservation still applies in both modes.)
 */
export async function discoverWorkflows(
  projectRoot: string = process.cwd(),
  agentFilter?: AgentType,
  options: { merge?: boolean } = {},
): Promise<DiscoveredWorkflow[]> {
  const { merge = true } = options;

  const localDir = getLocalWorkflowsDir(projectRoot);
  const globalDir = getGlobalWorkflowsDir();

  // Collect ALL builtin names (ignoring agentFilter) so reservation is
  // name-based across every agent: a local `ralph` for copilot is still
  // reserved by a builtin `ralph` for claude, even when the discovery
  // call was filtered to copilot.
  const [allBuiltins, globalResults, localResults] = await Promise.all([
    discoverBuiltinWorkflows(),
    discoverFromBaseDir(globalDir, "global", agentFilter),
    discoverFromBaseDir(localDir, "local", agentFilter),
  ]);
  const reservedNames = new Set<string>(allBuiltins.map((w) => w.name));
  const builtinResults = agentFilter
    ? allBuiltins.filter((w) => w.agent === agentFilter)
    : allBuiltins;

  // Drop any local/global workflow whose name matches a reserved
  // builtin. This happens BEFORE both merge and unmerged code paths so
  // reserved names never leak into `findWorkflow`, the picker, or
  // `--list` — there is exactly one canonical entry per reserved name,
  // the SDK-shipped one.
  const filteredGlobal = globalResults.filter((w) => !reservedNames.has(w.name));
  const filteredLocal = localResults.filter((w) => !reservedNames.has(w.name));

  if (!merge) {
    // Unmerged: keep local and global independent so `--list` can show
    // both copies of a non-reserved name when they coexist. Order lowest
    // → highest precedence so callers that want the winning entry can
    // take the last one by (agent, name).
    return [...filteredGlobal, ...filteredLocal, ...builtinResults];
  }

  // Merge with precedence: global (lowest) → local → builtin (highest).
  // Builtin is layered last as a belt-and-braces guarantee — though
  // reserved-name filtering above already makes this overwrite
  // impossible in practice.
  const byKey = new Map<string, DiscoveredWorkflow>();
  for (const wf of filteredGlobal) {
    byKey.set(`${wf.agent}/${wf.name}`, wf);
  }
  for (const wf of filteredLocal) {
    byKey.set(`${wf.agent}/${wf.name}`, wf);
  }
  for (const wf of builtinResults) {
    byKey.set(`${wf.agent}/${wf.name}`, wf);
  }

  return Array.from(byKey.values());
}

/**
 * Find a specific workflow by name and agent.
 */
export async function findWorkflow(
  name: string,
  agent: AgentType,
  projectRoot: string = process.cwd()
): Promise<DiscoveredWorkflow | null> {
  const all = await discoverWorkflows(projectRoot, agent);
  return all.find((w) => w.name === name) ?? null;
}

/**
 * A discovered workflow enriched with the metadata the picker needs to
 * render it: the human description and the declared input schema.
 *
 * Populated by {@link loadWorkflowsMetadata}, which runs each discovered
 * workflow through {@link WorkflowLoader.loadWorkflow} and extracts just
 * the display-relevant fields — the full compiled definition is
 * discarded after extraction so re-imports during execution are cheap.
 */
export interface WorkflowWithMetadata extends DiscoveredWorkflow {
  /** Workflow description, empty string when none was declared. */
  description: string;
  /** Picker-ready input schema; free-form workflows materialize a prompt field. */
  inputs: readonly WorkflowInput[];
}

/**
 * Load metadata (description + picker-ready inputs) for a batch of discovered workflows.
 *
 * Workflows that fail to import are **skipped silently** so one broken
 * entry can never prevent the picker from rendering. Callers that need
 * to surface load errors (e.g. `atomic workflow -n broken`) should use
 * {@link WorkflowLoader.loadWorkflow} directly — that path produces
 * structured error reports.
 */
export async function loadWorkflowsMetadata(
  discovered: DiscoveredWorkflow[],
): Promise<WorkflowWithMetadata[]> {
  const results = await Promise.all(
    discovered.map(async (wf): Promise<WorkflowWithMetadata | null> => {
      const loaded = await WorkflowLoader.loadWorkflow(wf);
      if (!loaded.ok) return null;
      return {
        ...wf,
        description: loaded.value.definition.description,
        inputs: loaded.value.definition.inputs,
      };
    }),
  );
  return results.filter(
    (r): r is WorkflowWithMetadata => r !== null,
  );
}

