/**
 * Workflow discovery — finds workflow definitions from disk.
 *
 * Workflows are discovered from:
 *   1. src/sdk/workflows/builtin/<name>/<agent>/index.ts (SDK-shipped builtins)
 *   2. .atomic/workflows/<name>/<agent>/index.ts (project-local)
 *   3. ~/.atomic/workflows/<name>/<agent>/index.ts (global)
 *
 * All three sources use the same scanning function (`discoverFromBaseDir`)
 * so registration is uniform. Builtin names are reserved — project-local
 * and global workflows with the same name are dropped during merge.
 */

import { join } from "node:path";
import { readdir } from "node:fs/promises";
import { homedir } from "node:os";
import ignore from "ignore";
import type { AgentType, WorkflowInput } from "../types.ts";
import { WorkflowLoader } from "./loader.ts";
import { IncompatibleSDKError } from "../errors.ts";

export interface DiscoveredWorkflow {
  name: string;
  agent: AgentType;
  path: string;
  source: "local" | "global" | "builtin";
}

function getLocalWorkflowsDir(projectRoot: string): string {
  return join(projectRoot, ".atomic", "workflows");
}

function getGlobalWorkflowsDir(): string {
  return join(homedir(), ".atomic", "workflows");
}

export const AGENTS: AgentType[] = ["copilot", "opencode", "claude"];
const AGENT_SET = new Set<string>(AGENTS);

/**
 * Default `.gitignore` content for a workflows directory.
 * Auto-generated during install; regenerated by discovery if missing.
 */
export const WORKFLOWS_GITIGNORE = [
  "node_modules/",
  "dist/",
  "build/",
  "coverage/",
  ".cache/",
  "*.log",
  "*.tsbuildinfo",
  "",
].join("\n");

/**
 * Load the `.gitignore` from a workflows directory, regenerating it if absent.
 * The workflows `.gitignore` is always auto-generated so a missing file
 * indicates an incomplete setup rather than an intentional absence.
 */
async function loadWorkflowsGitignore(workflowsDir: string): Promise<ignore.Ignore> {
  const gitignorePath = join(workflowsDir, ".gitignore");
  let content: string;
  try {
    content = await Bun.file(gitignorePath).text();
  } catch {
    // Missing — regenerate from the canonical template
    await Bun.write(gitignorePath, WORKFLOWS_GITIGNORE);
    content = WORKFLOWS_GITIGNORE;
  }
  return ignore().add(content);
}

/**
 * Discover workflows from a base directory by scanning workflow-name
 * directories first, then agent subdirectories within each.
 *
 * Layout: baseDir/<workflow_name>/<agent>/index.ts
 *
 * Entries are filtered against the `.gitignore` that lives inside the
 * workflows directory itself (auto-generated, regenerated if missing).
 */
async function discoverFromBaseDir(
  baseDir: string,
  source: "local" | "global" | "builtin",
  agentFilter?: AgentType,
): Promise<DiscoveredWorkflow[]> {
  const workflows: DiscoveredWorkflow[] = [];
  const agents = agentFilter ? [agentFilter] : AGENTS;
  const agentNames = new Set<string>(agents);

  let workflowEntries;
  try {
    workflowEntries = await readdir(baseDir, { withFileTypes: true });
  } catch {
    return workflows;
  }

  // Builtin workflows live inside the SDK source tree — skip .gitignore
  // handling to avoid writing files into node_modules or the SDK dir.
  const ig = source === "builtin"
    ? ignore()
    : await loadWorkflowsGitignore(baseDir);

  for (const wfEntry of workflowEntries) {
    if (!wfEntry.isDirectory()) continue;
    if (wfEntry.name.startsWith(".")) continue;
    // Skip agent-named directories at root (they are not workflow names)
    if (AGENT_SET.has(wfEntry.name)) continue;
    // Skip directories matched by the workflows .gitignore.
    // Append "/" so directory-only patterns (e.g. "build/") match correctly.
    if (ig.ignores(wfEntry.name + "/")) continue;

    const workflowDir = join(baseDir, wfEntry.name);

    let agentEntries;
    try {
      agentEntries = await readdir(workflowDir, { withFileTypes: true });
    } catch {
      continue;
    }

    for (const agentEntry of agentEntries) {
      if (!agentEntry.isDirectory()) continue;
      if (!agentNames.has(agentEntry.name)) continue;

      const indexPath = join(workflowDir, agentEntry.name, "index.ts");
      const file = Bun.file(indexPath);
      if (await file.exists()) {
        workflows.push({
          name: wfEntry.name,
          agent: agentEntry.name as AgentType,
          path: indexPath,
          source,
        });
      }
    }
  }

  return workflows;
}

/**
 * Absolute path to the `builtin/` directory inside the SDK source tree.
 * Computed from this file's URL so it always resolves correctly regardless
 * of how the package was installed (dev checkout, global, bunx, etc.).
 */
const BUILTIN_WORKFLOWS_DIR = join(
  Bun.fileURLToPath(new URL("../workflows/builtin", import.meta.url)),
);

/**
 * Discover all available workflows from built-in, global, and local sources.
 * Optionally filter by agent.
 *
 * **Merge precedence:** `builtin > local > global`.
 *
 * Builtin names are **strictly reserved** — a user-defined local or
 * global workflow whose name matches any built-in workflow is dropped
 * entirely from discovery. It will not be registered, returned from
 * `findWorkflow`, appear in the interactive picker, or show up in
 * `atomic workflow -l`. This protects SDK-shipped workflows (e.g.
 * `ralph`) from being silently overridden or even visibly "competing
 * with" a user's own definition, which would otherwise be confusing
 * when someone tries to run the canonical version.
 *
 * Reservation is by **name only**, across all agents: if a builtin
 * defines `ralph` for any agent, a local `ralph` for any other agent is
 * also dropped. Local still overrides global for every non-builtin
 * name, so project-scoped customisation of user-scoped workflows
 * continues to work.
 *
 * By default, the result is **merged by precedence** — if a workflow is
 * defined in both local and global sources, only the higher-precedence
 * entry is returned. This is the right shape for `findWorkflow`, which
 * needs the single resolved entry per (name, agent) pair.
 *
 * Pass `{ merge: false }` to get the **unmerged** result — local and
 * global contribute their entries independently, so `--list` can show
 * both a local and a global copy of the same workflow when they coexist
 * on disk. (Builtin reservation still applies in both modes.)
 */
export async function discoverWorkflows(
  projectRoot: string = process.cwd(),
  agentFilter?: AgentType,
  options: { merge?: boolean } = {},
): Promise<DiscoveredWorkflow[]> {
  const { merge = true } = options;

  const localDir = getLocalWorkflowsDir(projectRoot);
  const globalDir = getGlobalWorkflowsDir();

  // Collect ALL builtin names (ignoring agentFilter) so reservation is
  // name-based across every agent: a local `ralph` for copilot is still
  // reserved by a builtin `ralph` for claude, even when the discovery
  // call was filtered to copilot.
  const [allBuiltins, globalResults, localResults] = await Promise.all([
    discoverFromBaseDir(BUILTIN_WORKFLOWS_DIR, "builtin"),
    discoverFromBaseDir(globalDir, "global", agentFilter),
    discoverFromBaseDir(localDir, "local", agentFilter),
  ]);
  const reservedNames = new Set<string>(allBuiltins.map((w) => w.name));
  const builtinResults = agentFilter
    ? allBuiltins.filter((w) => w.agent === agentFilter)
    : allBuiltins;

  // Drop any local/global workflow whose name matches a reserved
  // builtin. This happens BEFORE both merge and unmerged code paths so
  // reserved names never leak into `findWorkflow`, the picker, or
  // `--list` — there is exactly one canonical entry per reserved name,
  // the SDK-shipped one.
  const filteredGlobal = globalResults.filter((w) => !reservedNames.has(w.name));
  const filteredLocal = localResults.filter((w) => !reservedNames.has(w.name));

  if (!merge) {
    // Unmerged: keep local and global independent so `--list` can show
    // both copies of a non-reserved name when they coexist. Order lowest
    // → highest precedence so callers that want the winning entry can
    // take the last one by (agent, name).
    return [...filteredGlobal, ...filteredLocal, ...builtinResults];
  }

  // Merge with precedence: global (lowest) → local → builtin (highest).
  // Builtin is layered last as a belt-and-braces guarantee — though
  // reserved-name filtering above already makes this overwrite
  // impossible in practice.
  const byKey = new Map<string, DiscoveredWorkflow>();
  for (const wf of filteredGlobal) {
    byKey.set(`${wf.agent}/${wf.name}`, wf);
  }
  for (const wf of filteredLocal) {
    byKey.set(`${wf.agent}/${wf.name}`, wf);
  }
  for (const wf of builtinResults) {
    byKey.set(`${wf.agent}/${wf.name}`, wf);
  }

  return Array.from(byKey.values());
}

/**
 * Find a specific workflow by name and agent.
 */
export async function findWorkflow(
  name: string,
  agent: AgentType,
  projectRoot: string = process.cwd()
): Promise<DiscoveredWorkflow | null> {
  const all = await discoverWorkflows(projectRoot, agent);
  return all.find((w) => w.name === name) ?? null;
}

/**
 * Load status for a {@link WorkflowWithMetadata} entry.
 *
 * - `ok`            — the workflow compiled cleanly and is ready to run.
 * - `incompatible`  — the workflow declared a `minSDKVersion` newer
 *                     than the bundled CLI. The CLI renders it with an
 *                     "update required" badge so users see the mismatch
 *                     rather than a silent disappearance.
 * - `error`         — any other load failure (syntax error, missing
 *                     `.compile()`, invalid default export, etc.).
 *                     Rendered with a "failed to load" badge plus the
 *                     underlying message.
 */
export type WorkflowMetadataStatus =
  | { kind: "ok" }
  | {
      kind: "incompatible";
      requiredVersion: string;
      currentVersion: string;
      message: string;
    }
  | {
      kind: "error";
      stage: "resolve" | "validate" | "load";
      message: string;
    };

/**
 * A discovered workflow enriched with the metadata the picker needs to
 * render it: the human description, the declared input schema, and the
 * load status.
 *
 * Populated by {@link loadWorkflowsMetadata}, which runs each discovered
 * workflow through {@link WorkflowLoader.loadWorkflow} and extracts the
 * display-relevant fields — the full compiled definition is discarded
 * after extraction so re-imports during execution are cheap.
 *
 * Broken entries still materialise with empty `description` / `inputs`
 * and a non-`ok` {@link status}, so the picker can render them as
 * visible "update required" / "failed to load" rows instead of
 * silently omitting them (the previous behaviour, which made user and
 * global workflows vanish whenever the base SDK shape drifted between
 * releases).
 */
export interface WorkflowWithMetadata extends DiscoveredWorkflow {
  /** Workflow description, empty string when none was declared or the workflow failed to load. */
  description: string;
  /** Picker-ready input schema; empty for free-form or failed-to-load workflows. */
  inputs: readonly WorkflowInput[];
  /** Load outcome — non-`ok` entries are rendered as visible diagnostics in the picker/list. */
  status: WorkflowMetadataStatus;
}

/**
 * Load metadata (description + picker-ready inputs + status) for a batch
 * of discovered workflows.
 *
 * **Failed workflows are kept in the returned list**, not dropped. Each
 * broken entry carries a {@link WorkflowMetadataStatus} explaining the
 * failure so the picker and `atomic workflow -l` can surface it as an
 * actionable diagnostic. This is the only way end users discover that a
 * workflow from an older SDK release has gone incompatible after an
 * `atomic` upgrade — silent filtering would leave them with a missing
 * entry and no breadcrumb.
 *
 * Callers that want to execute a workflow should still route through
 * {@link WorkflowLoader.loadWorkflow} — this function throws away the
 * compiled definition so re-running the loader on a confirmed pick is
 * unavoidable.
 */
export async function loadWorkflowsMetadata(
  discovered: DiscoveredWorkflow[],
): Promise<WorkflowWithMetadata[]> {
  return Promise.all(
    discovered.map(async (wf): Promise<WorkflowWithMetadata> => {
      const loaded = await WorkflowLoader.loadWorkflow(wf);
      if (loaded.ok) {
        return {
          ...wf,
          description: loaded.value.definition.description,
          inputs: loaded.value.definition.inputs,
          status: { kind: "ok" },
        };
      }

      // Incompatible SDK version is a first-class status so the UI can
      // show a dedicated "update required" hint. Every other failure
      // maps to a generic `error` variant — the picker renders the
      // message but doesn't try to interpret it further.
      if (loaded.error instanceof IncompatibleSDKError) {
        return {
          ...wf,
          description: "",
          inputs: [],
          status: {
            kind: "incompatible",
            requiredVersion: loaded.error.requiredVersion,
            currentVersion: loaded.error.currentVersion,
            message: loaded.message,
          },
        };
      }

      return {
        ...wf,
        description: "",
        inputs: [],
        status: {
          kind: "error",
          stage: loaded.stage,
          message: loaded.message,
        },
      };
    }),
  );
}

