import { useCallback } from "react";
import { appendCommandHistory } from "@/lib/ui/command-history.ts";
import { handleComposerSubmit } from "@/state/chat/composer/submit.ts";
import type { UseComposerControllerArgs } from "@/state/chat/composer/types.ts";
import { useComposerInputState } from "@/state/chat/composer/use-input-state.ts";

export function useComposerController({
  activeQuestion,
  addMessage,
  agentType,
  clipboard,
  clearDeferredCompletion,
  commandStyleIdRef,
  currentModelRef,
  emitMessageSubmitTelemetry,
  executeCommand,
  finalizeTaskItemsOnInterrupt,
  finalizeThinkingSourceTracking,
  getActiveStreamRunId,
  isStreamingRef,
  lastStreamingContentRef,
  messageQueue,
  onInterrupt,
  parallelAgentsRef,
  parallelInterruptHandlerRef,
  resolveTrackedRun,
  runningAskQuestionToolIdsRef,
  sendMessage,
  separateAndInterruptAgents,
  setIsStreaming,
  setMessagesWindowed,
  setParallelAgents,
  setTodoItems,
  setWorkflowSessionDir,
  setWorkflowSessionId,
  shouldHideActiveStreamContent,
  showModelSelector,
  stopSharedStreamState,
  streamingMessageIdRef,
  streamingMetaRef,
  streamingStartRef,
  todoItemsRef,
  updateWorkflowState,
  waitForUserInputResolverRef,
  workflowSessionDirRef,
  workflowSessionIdRef,
  workflowState,
  workflowTaskIdsRef,
}: UseComposerControllerArgs) {
  const {
    autocompleteSuggestions,
    handleAutocompleteIndexChange,
    handleAutocompleteSelect,
    handleBracketedPaste,
    handleInputChange,
    handleTextareaContentChange,
    handleTextareaCursorChange,
    historyIndexRef,
    historyNavigatingRef,
    inputScrollbar,
    isEditingQueue,
    kittyKeyboardDetectedRef,
    normalizePastedText,
    promptHistoryRef,
    savedInputRef,
    setIsEditingQueue,
    syncInputScrollbar,
    textareaKeyBindings,
    textareaRef,
  } = useComposerInputState({
    activeQuestion,
    addMessage,
    clipboard,
    commandStyleIdRef,
    executeCommand,
    showModelSelector,
    updateWorkflowState,
    workflowState,
  });

  const handleSubmit = useCallback(() => {
    handleComposerSubmit({
      addMessage,
      agentType,
      appendPromptHistory: (value) => {
        if (promptHistoryRef.current[promptHistoryRef.current.length - 1] !== value) {
          promptHistoryRef.current = [...promptHistoryRef.current, value];
          appendCommandHistory(value);
        }
        historyIndexRef.current = -1;
      },
      clearComposerAutocomplete: () => {
        if (workflowState.showAutocomplete || workflowState.argumentHint) {
          updateWorkflowState({
            showAutocomplete: false,
            autocompleteInput: "",
            selectedSuggestionIndex: 0,
            argumentHint: "",
          });
        }
      },
      clearDeferredCompletion,
      currentModelRef,
      emitMessageSubmitTelemetry,
      executeCommand,
      finalizeTaskItemsOnInterrupt,
      finalizeThinkingSourceTracking,
      getActiveStreamRunId,
      isStreamingRef,
      kittyKeyboardDetectedRef,
      lastStreamingContentRef,
      messageQueue,
      onInterrupt,
      parallelAgentsRef,
      parallelInterruptHandlerRef,
      resolveTrackedRun,
      runningAskQuestionToolIdsRef,
      sendMessage,
      separateAndInterruptAgents,
      setIsStreaming,
      setMessagesWindowed,
      setParallelAgents,
      setTodoItems,
      setWorkflowSessionDir,
      setWorkflowSessionId,
      shouldHideActiveStreamContent,
      stopSharedStreamState,
      streamingMessageIdRef,
      streamingMetaRef,
      streamingStartRef,
      textareaRef,
      todoItemsRef,
      updateWorkflowState,
      waitForUserInputResolverRef,
      workflowSessionDirRef,
      workflowSessionIdRef,
      workflowState,
      workflowTaskIdsRef,
    });
  }, [
    addMessage,
    agentType,
    currentModelRef,
    clearDeferredCompletion,
    emitMessageSubmitTelemetry,
    executeCommand,
    finalizeTaskItemsOnInterrupt,
    finalizeThinkingSourceTracking,
    getActiveStreamRunId,
    isStreamingRef,
    lastStreamingContentRef,
    messageQueue,
    onInterrupt,
    parallelAgentsRef,
    parallelInterruptHandlerRef,
    resolveTrackedRun,
    runningAskQuestionToolIdsRef,
    sendMessage,
    separateAndInterruptAgents,
    setIsStreaming,
    setMessagesWindowed,
    setParallelAgents,
    setTodoItems,
    setWorkflowSessionDir,
    setWorkflowSessionId,
    shouldHideActiveStreamContent,
    stopSharedStreamState,
    streamingMessageIdRef,
    streamingMetaRef,
    streamingStartRef,
    todoItemsRef,
    updateWorkflowState,
    waitForUserInputResolverRef,
    workflowSessionDirRef,
    workflowSessionIdRef,
    workflowState,
    workflowTaskIdsRef,
  ]);

  return {
    autocompleteSuggestions,
    handleAutocompleteIndexChange,
    handleAutocompleteSelect,
    handleBracketedPaste,
    handleInputChange,
    handleSubmit,
    handleTextareaContentChange,
    handleTextareaCursorChange,
    historyIndexRef,
    historyNavigatingRef,
    inputScrollbar,
    isEditingQueue,
    kittyKeyboardDetectedRef,
    normalizePastedText,
    promptHistoryRef,
    savedInputRef,
    setIsEditingQueue,
    syncInputScrollbar,
    textareaKeyBindings,
    textareaRef,
  };
}
