name: Test Devcontainer Features

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: "Test global cross-feature scenarios"
        run: devcontainer features test --global-scenarios-only --project-folder ./devcontainer-features
